name: Check Manifest XML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

concurrency:
  group: ci-build-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  manifest-kmconfig:
    name: check manifest repo build
    runs-on: [ self-hosted]
    steps:
    - name: Runner workspace git objects cleanup
      run : |
          echo "Cleaning up git objects"
    - name: GitHub Checkout Action
      uses: actions/checkout@v3
    - name: get hash and list of file changes
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo $git_hash
        git_branch=${GITHUB_REF#refs/heads/}
        echo $git_branch
        ls 
        pwd
        df
        #./build.sh $git_hash
